services:
  database:
    image: timescale/timescaledb-ha:pg17
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
      TZ: "UTC"
    ports:
      - "${DOCKER_DATABASE_PORT}:5432"
    volumes:
      - ./.docker/timescaledb_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "${DOCKER_REDIS_PORT:-6379}:6379"
    volumes:
      - ./.docker/redis_data:/data
